FROM ubuntu:xenial
LABEL maintainer="Quentin Plessis <plequen00@gmail.com>"

RUN apt-get update && apt-get install -y \
    software-properties-common \
    python-software-properties \
    supervisor \
  && rm -rf /var/lib/apt/lists/*

# --------------------
# Pharo
# --------------------
RUN dpkg --add-architecture i386 && apt-get update && apt-get install -y \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
    libfreetype6:i386 \
    libssl1.0.0:i386 \
    zlib1g:i386 \
    libgl1-mesa-glx:i386 \
    libx11-6:i386 \
    libasound2:i386 \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir pharo && cd pharo \
  && apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
  && curl get.pharo.org/50+vm | bash \
  && mv ../pharo /usr/local/bin/ \
  && apt-get remove -y \
    unzip \
  && rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/local/bin/pharo:${PATH}"

# --------------------
# VNC
# --------------------
RUN apt-get update && apt-get install -y \
    xvfb \
    x11vnc \
    icewm \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 5900

# --------------------
# Setup
# --------------------

ADD ./launch-pharo.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/launch-pharo.sh
ADD ./setup-vnc.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/setup-vnc.sh
ADD ./setup.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/setup.sh

# --------------------
# Workspace
# --------------------

COPY images /root/images

WORKDIR /root/data

RUN cp /usr/local/bin/pharo/Pharo.* /root/data

VOLUME [ "/root/data" ]

EXPOSE 9000

# --------------------
# Supervisor
# --------------------
COPY pharo-supervisord.conf /etc/supervisor/conf.d/pharo-supervisord.conf


CMD [ "/bin/bash", "-l", "-c", "/usr/local/bin/setup.sh && /usr/bin/supervisord -n" ]
